### PR TITLE
Do not use environment marker for importlib-metadata

### PR DESCRIPTION
**Pull request by fridex**
Fixes: #607

### CODE REVIEW

**Comment by fridex** [comment]
This solution is not nice as thoth-solver will inject Python 3.8 libs to Python 3.7 environment that could introduce other issues. However, we do not ship pip in Fedora 32 for Python 3.7 and other installation method is also not streightforward. Ideally, we should declare solver-fedora-32-py37 as not the right environment to be used. Let's see...

**Review by harshad16 — APPROVED** [review]
lgtm
good catch on python 3.8 and python3.7 in fedora32
should we make a new release?

**Comment by fridex** [comment]
> should we make a new release?

Yes, once the fix is merged. :+1:

**Pull request merged**
