### PR TITLE
[WIP] Use sequence instead of raw strings

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
Related: https://github.com/thoth-station/package-extract/pull/8, https://github.com/kennethreitz/delegator.py/pull/52

**Comment by goern** [comment]
@fridex is this still relevant? we are waiting on upstream fixes?

**Comment by goern** [comment]
@fridex is this still relevant? we are waiting on upstream fixes?

**Comment by fridex** [comment]
> @fridex is this still relevant? we are waiting on upstream fixes?

yes, I will have a look at it, there are some review comments to target.

**Comment by fridex** [comment]
If upstream is not willing to fix the current behavior, we can still do `shlex.quote()` and pass quoted strings instead.

**Comment by goern** [comment]
recheck

**Comment by goern** [comment]
is this still valid?

**Pull request closed without merging**
