### PR TITLE
Remove Fedora that is EOL

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

Closes: https://github.com/thoth-station/solver/issues/5056
Closes: https://github.com/thoth-station/solver/issues/5058

### CODE REVIEW

**Comment by fridex** [comment]
/assign @harshad16 

PTAL if there needs to be done anything else. It might be nice to also purge quay repository eventually as prescriptions-refresh job queries container images available there.

**Comment by harshad16** [comment]
> PTAL if there needs to be done anything else. It might be nice to also purge quay repository eventually as prescriptions-refresh job queries container images available there.

definitely, however, I checked this is no archived option in quay, so the purging is the only option.

**Review by harshad16 — APPROVED** [review]
lgtm
thanks :100:

**Comment by fridex** [comment]
> > PTAL if there needs to be done anything else. It might be nice to also purge quay repository eventually as prescriptions-refresh job queries container images available there.
> 
> definitely, however, I checked this is no archived option in quay, so the purging is the only option.

Thanks. Let's see how to do it 👍🏻 

/approve

**Pull request merged**
