### PR TITLE
Adjust links and link to solvers built on quay

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
@harshad16 do we want to maintain this listing here? It might give some order to the images present on the quay. We might eventually remove the old ones.

**Review by goern — APPROVED** [review]

**Comment by harshad16** [comment]
> do we want to maintain this listing here? It might give some order to the images present on the quay. We might eventually remove the old ones.

@fridex we can definitely have them here. 
thanks for adding

**Pull request merged**
