### PR TITLE
Be consistent with labels on solvers

### PR DESCRIPTION
**Pull request by fridex**
Depends-On: https://github.com/thoth-station/common/pull/462

### CODE REVIEW

**Comment by fridex** [comment]
We have `component=graph-sync` and `graph-sync-type=inspection` in graph syncs. Let's be consistent here.

**Comment by fridex** [comment]
This will introduce https://github.com/thoth-station/solver/issues/273

**Comment by harshad16** [comment]
@fridex Dependent PR is reviewed and merged.

**Comment by fridex** [comment]
> @fridex Dependent PR is reviewed and merged.

Thanks! Dropped WIP labels. :+1:

**Pull request merged**
