### PR TITLE
Remove Fedora 31 + Python 3.7 it went EOL

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/s2i-thoth/pull/191

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
/assign @harshad16

... we can remove others as well after this gets merged 👍🏻

**Comment by goern** [comment]
Dont we have to reconfigure something in thoth-application/ too?

**Comment by fridex** [comment]
> Dont we have to reconfigure something in thoth-application/ too?

No, we do not have the $SUBJ solver enabled in any deployment. Others can be removed once this gets merged (as commented above).

**Comment by goern** [comment]
@harshad16 can we merge this?

**Review by harshad16 — APPROVED** [review]
/lgtm
/approve
thanks :100:

**Pull request merged**
